In [95]:
import pandas as pd
test = pd.read_csv('/Users/miji.lee/Downloads/titanic/test.csv')
train = pd.read_csv('/Users/miji.lee/Downloads/titanic/train.csv')
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [ ]:
# missing values

train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [98]:
train.duplicated().sum()
# train.drop_duplicates(subset =['PassengerId'], inplace = True)

np.int64(0)

In [99]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [100]:
train[train['Age']<1].head()
# dataset[select rows that meet the condition]

PassengerId  Survived  Pclass                            Name     Sex  \
78            79         1       2   Caldwell, Master. Alden Gates    male   
305          306         1       1  Allison, Master. Hudson Trevor    male   
469          470         1       3   Baclini, Miss. Helene Barbara  female   
644          645         1       3          Baclini, Miss. Eugenie  female   
755          756         1       2       Hamalainen, Master. Viljo    male   

      Age  SibSp  Parch  Ticket      Fare    Cabin Embarked  
78   0.83      0      2  248738   29.0000      NaN        S  
305  0.92      1      2  113781  151.5500  C22 C26        S  
469  0.75      2      1    2666   19.2583      NaN        C  
644  0.75      2      1    2666   19.2583      NaN        C  
755  0.67      1      1  250649   14.5000      NaN        S

In [101]:
train[(train['Age']>=1)& (train['Age']<=2)].head()
# 복수 조건을 두개 만족해야 할때는 dataset[(select rows with condition 1) & (select rows with condition 2)]

PassengerId  Survived  Pclass                               Name     Sex  \
7              8         0       3     Palsson, Master. Gosta Leonard    male   
16            17         0       3               Rice, Master. Eugene    male   
119          120         0       3  Andersson, Miss. Ellis Anna Maria  female   
164          165         0       3       Panula, Master. Eino Viljami    male   
172          173         1       3       Johnson, Miss. Eleanor Ileen  female   

     Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
7    2.0      3      1   349909  21.0750   NaN        S  
16   2.0      4      1   382652  29.1250   NaN        Q  
119  2.0      4      2   347082  31.2750   NaN        S  
164  1.0      4      1  3101295  39.6875   NaN        S  
172  1.0      1      1   347742  11.1333   NaN        S

In [102]:
# training에서 어떤 피쳐가 예측값에 가장 영향을 많이 미치나 파악해야
# 어떤 상관관계를 맺고 있나 -> heatmap (only continuous. category식 데이터는 어려움)
corr_matrix = train.corr(numeric_only= True)
# 문자열 데이터와 같이 숫자가 없는 데이터간 상관관계는 논리적으로 말이 안됨 -> 수치형만 포함시키도록
# 그 수치형이 ID같은 범주형 데이터라도 어느정도 상관관계가 보여짐

corr_matrix
# pearson correlation. 1에 가까우면 한 피쳐가 증가하면 다른 피쳐도 증가. -1은 역관계

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [103]:
import plotly.express as px

fig_px = px.imshow(corr_matrix, text_auto=True, aspect='auto', 
          title= 'Correlation Heatmap', 
          color_continuous_scale='Blues')

fig_px.show()
#  알고 싶은 것은 survived 이므로 그것과 다른 변수간의 관계를 중점으로 봄
#  fare색상이 진해보임

In [104]:
# 히트맵으로 안나오는 카테고리형 데이터와 survived의 관계를 알아보자 
survived = train[train['Survived']==1]['Sex'].value_counts()
# survived 칼럼== 1 조건을 만족하는 row number를 뽑아서 train 데이터셋으로 새로운 데이터프레임의 sex칼럼을 뽑음
# 갯수 셈
survived

Sex
female    233
male      109
Name: count, dtype: int64

In [105]:
dead = train[train['Survived']==0]['Sex'].value_counts()
dead

Sex
male      468
female     81
Name: count, dtype: int64

In [ ]:
df_0 = pd.DataFrame([survived, dead])
df_0
# 만약 'survived', 'dead'처럼 감싸면 
# 0 survived
# 1 dead 처럼 단순한 문자열로 인식.

# survived, dead는 세로로 된 series같이 보이지만 사실은 가로 행으로 구성되있음
# 행데이터들을 pd.DataFrame은 세로로 합친 것

Sex    female  male
count     233   109
count      81   468

In [185]:
df_0.index = ['Survived', 'Dead']
# index: 맨 앞 칼럼
df_0

Sex       female  male
Survived     233   109
Dead          81   468

In [ ]:
# 동일하게 concat으로 할수도 있음

df1 = pd.concat([survived, dead], axis =1)
# 1은 옆으로 늘고 0은 위아래로 늘음
df1.columns = ['Survived','Dead']git
print(df1)

        Survived  Dead
Sex                   
female       233    81
male         109   468


In [ ]:
result = []  # feature 이름을 key로, DataFrame을 value로
features = ['Sex', 'Pclass']

def fct(feature):
    for feature in features:
        survived =train[train['Survived']==1][feature].value_counts()
        dead = train[train['Survived']==0][feature].value_counts()
        df_graph = pd.DataFrame([survived, dead])
        df_graph.index = ['Survived', 'Dead']
        result.append(df_graph)
        result_df = pd.concat(result, axis =0)
    return result_df

# 함수 실행 후 반환값을 변수에 저장
result_1 = fct(features)


female   male      1      3     2
Survived   233.0  109.0    NaN    NaN   NaN
Dead        81.0  468.0    NaN    NaN   NaN
Survived     NaN    NaN  136.0  119.0  87.0
Dead         NaN    NaN   80.0  372.0  97.0

In [175]:
# 같은 내용을 재활용을 위해 함수로 바꾸면

def visualisation(feature):
    survived =train[train['Survived']==1][feature].value_counts()
    dead = train[train['Survived']==0][feature].value_counts()
    df_graph = pd.DataFrame([survived, dead])
    df_graph.index = ['Survived', 'Dead']
    return df_graph

In [184]:
df_visual = visualisation('Sex')
df_visual.head()

Sex       female  male
Survived     233   109
Dead          81   468

In [202]:
# 절대 빈도는 막대 그래프 (남자에 비해 여자가 더 많이 살았다)
# 상대 빈도는 파이 차트 (여자 중 사망한 %)

fig  = px.bar(df_0,
       x = df_0.index,
       y = df_0.columns,
       barmode = 'group',
        text_auto = True,
       title ='Survived Count by Sex')

fig.show()

In [208]:
df_pc = visualisation('Pclass')
df_pc

Pclass      1    3   2
Survived  136  119  87
Dead       80  372  97

In [211]:
fig = px.bar(df_pc,
       x=df_pc.index,
       y=df_pc.columns,
       barmode ='stack',
       text_auto = True,
       title ='Survived Count by Class')
fig.show()

In [ ]:
# 등급을 x축에 놓고 등급별로 확인하려면 plotly 특성상 x축은 인덱스만 쓸 수 있음
# 지금 인덱스는 생존 여부이므로 transpose

df_transpose = df_pc.transpose()
df_transpose

Survived  Dead
Pclass                
1            136    80
3            119   372
2             87    97

In [246]:
fig = px.bar(df_transpose,
       x=df_transpose.index,
       y=df_transpose.columns,
       barmode ='stack',
       text_auto = True,
       title ='Survived Count by Class')
fig.show()

In [ ]:
# 연습: reset_index() 와 melt() 로 롱폼 만들기

df_pc_reset = df_pc.reset_index()
df_pc_reset = df_pc_reset.rename(columns = {'index': 'Survival'})
df_pc_reset.index.name =None
# reset_index(): melt하려면 기준으로 두는 칼럼이 인덱스여서는 안됨. 칼럼이어야 됨.
# 나는 survival 여부를 기준으로 롱폼 만들고 싶은데 df_pc상태에서는 그게 인덱스로 설정되있음
# 그래서 얘를 컬럼으로 빼서 사용될 수 있게 함.

In [ ]:
df_pc_reset = df_pc_reset.melt(id_vars='Survival', var_name='PClass', value_name = 'Number')
df_pc_reset
# melt 는 옆으로 긴 데이터프레임을 아래로 길게 늘어뜨리는 것
# id vars: 어떤 칼럼을 그대로 두고 녹일것인가
# var name: 녹일 열 이름을 담을 컬럼 이름
# value_name: 값이 들어갈 컬럼 이름

Survival PClass  Number
0  Survived      1     136
1      Dead      1      80
2  Survived      3     119
3      Dead      3     372
4  Survived      2      87
5      Dead      2      97

In [212]:
fig = px.pie(data_frame = df_0,
             names = df_0.index, 
             values = 'female',
             title = 'Survival Ratio of Women')

fig.show()

In [248]:
df_pc

Pclass      1    3   2
Survived  136  119  87
Dead       80  372  97

In [ ]:
# 여러개 파이 차트를 한 화면에 동시에 올린다 -> domain
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(
    go.Pie(
        labels = df_pc.index,
        values = df_pc[1],
        domain = {'x': [0.0,0.33]}
    )
)

fig.add_trace(
    go.Pie(
        labels = df_pc.index,
        values = df_pc[2],
        domain = {'x': [0.33,0.66]}
    )
)

fig.add_trace(
    go.Pie(
        labels = df_pc.index,
        values = df_pc[3],
        domain = {'x': [0.66,1.0]}
    )
)

fig.update_layout(
    annotations = [dict(
                    text = '1st class',
                    x = 0.165,
                    y=1.1,
                    showarrow =False
                    ),
    dict(text = '3rd class',
         x=0.495,
         y=1.1,
        showarrow =False
),
    dict(text = '2nd class',
         x = 0.83,
         y=1.1,
        showarrow =False
)
            ]
        )

fig.show()


In [264]:
words = ['apple', 'dog', 'banana', 'cat']
long_words = []

for w in words:
    if len(w)>=4:
        long_words.append(w)

long_words


['apple', 'banana']

In [266]:
df_eb = visualisation('Embarked')
df_eb_tr = df_eb.transpose()
df_eb_tr

Survived  Dead
Embarked                
S              217   427
C               93    75
Q               30    47

In [267]:
px.bar(data_frame = df_eb_tr,
       x = df_eb_tr.index,
       y = df_eb_tr.columns,
       barmode = 'stack',
       text_auto = True, 
       title = 'Survival by Embarked')

In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Pie(
        labels = df_eb.index,
        values = df_eb.iloc[:,0], 
        # iloc에서 0번째 칼럼은 인덱스가 아니라 1번째 칼럼
        # iloc은 칼럼 순서 정수로만 쓸 수 있음. 칼럼 '이름'으로 선택하려면 loc[:,'name'] 
        domain = {'x': [0.0,0.33]}
    )
)

fig.add_trace(
    go.Pie(
        labels =  df_eb.index,
        values = df_eb.iloc[:,1],
        domain = {'x': [0.33,0.66]}
    )
)

fig.add_trace(
    go.Pie(
        labels = df_eb.index,
        values = df_eb.iloc[:,2],
        domain = {'x': [0.66,1.0]}
    )
)

fig.update_layout(
    annotations = [dict(
                    text = 'S',
                    x = 0.165,
                    y=1.1,
                    showarrow =False
                    ),
    dict(text = 'C',
         x=0.495,
         y=1.1,
        showarrow =False
),
    dict(text = 'Q',
         x = 0.83,
         y=1.1,
        showarrow =False
)
            ]
        )

fig.show()


In [ ]:
#  numpy practice

import numpy as np

list1 = [1,2,3]

array1 = np.array(list1)
print(type(array1)) # 1차원. 바깥 []안에 []로 감싸진 것만 어레이로 인식되고, 행과 열을 가진 2차원 matrix로 인식되기 시작 
# 만약 안쪽 []없이 그냥 숫자만 있으면 그건 그냥 숫자 나열(벡터)로 인식되고, 행도 열도 아닌 그냥 1차원
# 2차원이면 (행 1,열 3) 이지만, 1차원이면 걍 (3,)으로 아예 행 자체가 성립이 안됨
# ,만 들어가면 무조건 1차원
print(array1.shape)


array2= np.array([[1,2,3], [4,5,6]])
# 바깥 [] 안의 []는 행 바꿔쓰기를 의미함. [1,2,3]
                                # [4,5,6] -> 행 2개 열 3개 (2,3) 
# 리스트 2개고 2차원
print(type(array2))
print(array2.shape)


array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)
# 처음 예제와 달리 안쪽 []로 한번 더 감싸짐 -> 비로소 행렬로 인식됨.
# [1,2,3] 같이 행 1줄이고 열 3개인 2차원 매트릭스

<class 'numpy.ndarray'>
(3,)
int64
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [ ]:
# 데이터 타입 통일

# 원래 array안의 데이터 타입은 무조건 동일해야. [1, 2.3] 이런거 안됨
# 하지만 들어가기 위해 어레이가 자동으로 형변환시켜줌 -> [1.0, 2.3] 처럼
array1 = np.array([1,2, 'test'])
print(array1) # test가 문자열이니 통일시키려고 1,2도 문자열로 변경됨
array1.dtype

['1' '2' 'test']


dtype('<U21')

In [290]:
# astype

array_int = np.array([1,2,3])
array_int.astype('float64')

array([1., 2., 3.])

In [ ]:
# axis 구분

# 행 방향부터 가장 큰 axis를 부여하고, 역방향으로 내려옴
# [1,2,3] 같이 벡터인 1차원 배열은 애초에 행은 1로 고정이고 열밖에 없으니 axis = 0은 가로방향
# [[1,2,3]
#   [4,5,6]] 같이 2차원 배열은 axis가 0,1밖에 없음. 그 중 axis = 1이 크니, 이것은 가로 방향에 배정되고 세로 방향은 남은 axis = 0\


In [295]:
# numpy 편하게 생성하기 
# 만들어지는 데이터의 쉐입은 아는데 값은 몰라서 프레임만 필요할 때
array_row =np.arange(10) # 순서대로 연속값 
                        # 10개의 원소. 0칼럼부터 9칼럼까지
print(array_row)
array_row.shape  # 1차원

zero_array = np.zeros([3,2], dtype = 'int32')
print(zero_array)

ones_array = np.ones([3,2], dtype = 'int32')
print(ones_array)

[0 1 2 3 4 5 6 7 8 9]
[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [ ]:
# ndarray의 차원 , 모양 변경

print(array_row) # 원본: 10개 원소, 1차원
array_row.reshape(5,2) # 2차원 5행 2열로 바꿔줘
array_row.reshape(-1,5) # -1는 가변적. 알아서 행 갯수가 열갯수 5개에 맞게 바꿔달라. 
# 원소가 10개인데 reshape(2,7) 같이 안맞는 갯수로 요청하면 에러


# 1차원으로 바꾸려면 
array2 = np.array([[1,2,3], [4,5,6]])
array2.reshape(-1,) 
#  

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6])

In [321]:
# 단일 indexing

# 1차원

array1 = np.arange(start =1, stop = 10)
print(array1)
print(array1[0]) # array 다음 []은 인덱싱 위치 빼달라는 의미 

print(array1[-1]) # 맨 뒷값
print(array1[-2]) # 맨 뒷값에서 다시 뒤로


# 2차원

array2 = array1.reshape([3,3])
print(array2)
print(array2[0,1]) # 0행 1열

[1 2 3 4 5 6 7 8 9]
1
9
8
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [330]:
# 슬라이싱 인덱싱 - 연속 인덱싱

# 1차원

print(array1)
array1[0:3] # 0,1,2 인덱스. 마지막은 포함 안함
array1.shape # 여전히 1차원

array1[3:]
array1[:]

# 2차원

print(array2)
array2[0:1,0:2]
array2[:,:]
array2[:2, 1:] # 마지막 숫자 2는 해당되지 않는걸 잊지말라구
array2[:1, 0]

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1])

In [ ]:
# 불연속 인덱싱

array2[[0,1],2]
array2[[0,1],:1]
array2[[0,1]] # 따로 열값 기재 안됐으면 전체

array1[array1>2] # 조건만 넣는 것도 가능

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 순서 정렬

# 1차원

array1 = np.array([3,1,9,5])
np.sort(array1)
print(array1) # np.sort 는 원본 순서가 바뀌지 않음. 
array_new = np.sort(array1)

array1.sort()
print(array1) # ndarray.sort 역시 정렬은 동일하나, 원본 자체를 바꿈


# 내림차순 정렬

array2 = np.array([3,1,9,5])
np.sort(array2)[::-1]

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]


In [ ]:
# 순서 정렬 2차원

array2 = np.array([[8,12], [7,1]])

np.sort(array2, axis= 1) # 2차원에서 큰 값인 axis=1부터, row방향부터 시작함
np.sort(array2, axis = 0) 

array([[ 7,  1],
       [ 8, 12]])

In [ ]:
# 원본의 인덱스 그대로 순서 정렬 시켜서 반환 

# 오름차순
array1 = np.array([3,1,9,5])
np.argsort(array1)

# 내림차순
np.argsort(array1)[::-1]

# 쓰임새
# key, value로 매핑을 해야 할 때

name_array = np.array(['A', 'B', 'C', 'D', 'E'])
score_array = np.array([78,95,84,98,88])
# 성적 좋은 순으로 사람명 매핑하고 싶은데 그냥 sort하면 순서가 다 틀어짐
sort_score = np.argsort(score_array) # 성적 좋은 순으로 인덱스
name_array[sort_score] # 어레이[숫자] 면 인덱싱 되는 것에 착안해서


array(['A', 'C', 'E', 'B', 'D'], dtype='<U1')

### 판다스

데이터 프레임은 열, 행 둘 다 있는 2차원 데이터셋
시리즈는 열 존재 안하고 행만 있는 1차원. 열 존재하면 2차원 데이터 프레임이 됨.
넘파이의 1차원은 열도 행도 존재 안함.

In [ ]:
train['Pclass'].value_counts()
# pclass가 null 처리된 줄은 세지 않는 것이 문제
# 만약 전체의 70%가 NaN일 경우는 잘못 판단할수도 있음

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [368]:
# convert DataFrame to numpy

dict= {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)

df_array = df_dict.values
type(df_array)

# numpy to list

df_array.tolist()

[[1, 2, 3], [11, 22, 33]]

In [376]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  practice  
0      0         A/5 21171   7.2500   NaN        S     122.0  
1      0          PC 17599  71.2833   C85        C     138.0  
2      0  STON/O2. 3101282   7.9250   NaN        S     126.0  
3      0            113803  53.1000  C123        S     135.0  
4      0            373450   8.0500   NaN        S     135.0

In [ ]:
# 새 컬럼 생성, 수정

train['practice'] = train['Age']+100
train.head()

# 칼럼 삭제

train_drop = train.drop('practice', axis = 1) # 보통 칼럼을 삭제하므로 axis = 1이 흔함
                                            # row 삭제한다면 액시스 0
                                        # 디폴트가 inplace = False
train_drop.head()

# 여러 칼럼 동시에 삭제

train_drop.drop(['Age', 'Parch'], axis = 1, inplace = True) # axis 명시 안하면 오류
print(train_drop.head())


# 행 삭제

train_drop.drop([0,1,2], axis = 0, inplace = True)
print(train_drop.head()) # 3,4,5부터 시작함

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  SibSp  \
0                            Braund, Mr. Owen Harris    male      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1   
2                             Heikkinen, Miss. Laina  female      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1   
4                           Allen, Mr. William Henry    male      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S  
   PassengerId  Survived  Pclass  \
3            4         1       1   
4       